apiVersion: v1
kind: Pod
metadata:
        name: client-pod
        labels:
                component: web
spec:
        containers:
                - name: client
                  image: swastiksuman/springboot-docker-webapp
                  ports:
                        - containerPort: 8080
